#!/bin/bash
#SBATCH -J sample_ICP_job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=00:30:00
#SBATCH --mem-per-cpu=3G
#SBATCH --output warpx.%j.out

# setup environment
module purge
module load /home/bj8080/Modules/modulefiles/warpx_icp_stabilization/1.0

# Name the input file and output directory
RUNFILE="inputs.py"
OUTFILE="diags_output"

# copy the input file and submission script to the output directory
mkdir -p "$OUTFILE"
cp "$RUNFILE" "$OUTFILE"
cp "$0" "$OUTFILE"

# Set parameters and run simulation
ARGS=( # Note: Bash arrays support inline comments, unlike backslash-continued commands we had before
    --dz 2.e-5                      # Cell size
    --dt 5e-12                      # Time step
    --ICP_mag 300.                  # ICP current source strength [A/m^2]
    --ICP_freq 10e6                 # ICP source frequency
    --Nppc 20                       # Number of particles per cell
    --initial_density 5e15          # Initial plasma density [m^-3], should be near the expected final density
    --convergence_periods 0.      # Number of ICP periods in the convergence window
    --diagnostic_periods 20.        # Number of ICP periods in the diagnostic window
    --collections_per_period 25     # Number of collection steps per ICP period
    --solver rk4                    # euler, rk2, rk4, ab2
)
mpirun -n 24 python "$RUNFILE" -d "$OUTFILE" "${ARGS[@]}"
