name: 🐧 HIP

on:
  push:
    branches:
      - "development"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-hip
  cancel-in-progress: true

jobs:

  check_changes:
    name: Analyze
    uses: ./.github/workflows/check_changes.yml
